<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eetu Tammi">

<title>Customer Purchase Behavior Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="olist_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="olist_analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="olist_analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="olist_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="olist_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="olist_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="olist_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="olist_analysis_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="olist_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="olist_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="olist_analysis_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Customer Purchase Behavior Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eetu Tammi </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This project analyzes customer purchasing behavior using the Olist Brazilian E-Commerce Public Dataset.</p>
<p>The analysis focuses on customer retention, purchasing behavior, and customer value, with the aim of understanding why some customers return and why some customers generate substantially more revenue than others.</p>
<p>The first research question is:</p>
<p><strong>How common are repeat purchases, and what characteristics of the first purchase are associated with customers returning?</strong></p>
<p>The analysis examines the frequency of repeat purchases, the time between the first and second order, differences between repeat and non-repeat customers, the relationship between first-order product categories and repeat purchasing, and whether repeat purchases can be predicted using information available from the first order.</p>
<p>The second research question is:</p>
<p><strong>Which customers are most valuable, and can high-value customers be identified using information from their first purchase?</strong></p>
<p>The analysis examines the distribution of customer spending, the concentration of revenue among high-value customers, differences in customer value across first-order categories, and whether high-value customers can be identified using characteristics of their first purchase.</p>
<p>The third research question is:</p>
<p><strong>How is delivery performance associated with customer satisfaction and repeat purchasing?</strong></p>
<p>The analysis examines whether late deliveries are associated with lower review scores and lower repeat-purchase rates.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>The analysis uses five datasets from the Olist e-commerce dataset:</p>
<ul>
<li>orders</li>
<li>customers</li>
<li>order items</li>
<li>products</li>
<li>reviews</li>
</ul>
<p>The analysis focuses on customer orders, repeat purchasing, first-order characteristics, product categories, delivery experience, and customer reviews.</p>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data Preparation</h2>
<p>The analysis uses <code>customer_unique_id</code> as the customer identifier. The <code>customer_id</code> in the orders data identifies a customer record, so orders are linked to the customer data and grouped using <code>customer_unique_id</code> to identify individual customers across orders.</p>
<p>Orders are sorted by purchase timestamp for each customer, allowing the first and second orders to be identified. A repeat purchase is defined as a second order occurring at least one day after the first order. Customers without a qualifying second order are classified as non-repeat customers.</p>
<p>For the first order, additional characteristics are collected, including order value, number of items, freight value, delivery time, product category, and review score. These variables are used to compare repeat and non-repeat customers and to evaluate whether repeat purchases can be predicted from information available at the first purchase.</p>
<p>Delivery performance is also included in the first-order data. Delivery time and whether the order was delivered later than the estimated delivery date are used to examine the relationship between delivery performance, customer satisfaction, and repeat purchasing.</p>
<p>In addition, all orders are aggregated at the customer level to measure customer value. Total spending, number of orders, number of items, average order value, and other customer-level measures are calculated. Customers in the top 10% of total spending are classified as high-value customers. These measures are then used to examine revenue concentration and whether high-value customers can be identified from characteristics of their first purchase.</p>
</section>
<section id="research-question-1-repeat-purchases" class="level2">
<h2 class="anchored" data-anchor-id="research-question-1-repeat-purchases">Research Question 1: Repeat Purchases</h2>
<section id="question" class="level3">
<h3 class="anchored" data-anchor-id="question">Question</h3>
<p><strong>How common are repeat purchases, what characteristics are associated with customers returning, and can repeat purchases be predicted from information available at the first purchase?</strong></p>
<p>The aim of this part of the analysis is to understand customer retention and identify patterns associated with repeat purchasing. The analysis first examines how common repeat purchases are and how long customers typically take to place a second order.</p>
<p>The analysis then compares repeat and non-repeat customers based on characteristics of their first purchase, including order value, number of items, freight value, delivery time, product category, and review score. Finally, a logistic regression model is used to evaluate whether repeat purchases can be predicted using information available from the first order.</p>
</section>
<section id="how-common-are-repeat-purchases" class="level3">
<h3 class="anchored" data-anchor-id="how-common-are-repeat-purchases">How common are repeat purchases?</h3>
<p>The analysis identified 96,096 unique customers. Of these, 2,070 customers made an observed repeat purchase, corresponding to a repeat purchase rate of approximately 2.2%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-repeat-rate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repeat-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="olist_analysis_files/figure-html/fig-repeat-rate-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repeat-rate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Observed repeat purchase among unique customers.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The result shows that repeat purchasing is relatively uncommon in the observed data. Approximately <strong>97.8%</strong> of customers did not have an observed second purchase, while only <strong>2.2%</strong> made a qualifying repeat purchase.</p>
<p>This result should be interpreted with some caution. The dataset covers a limited observation period, meaning that customers who made their first purchase near the end of the period may not have had enough time to return. Therefore, the observed repeat purchase rate should not be interpreted as a complete measure of long-term customer retention.</p>
</section>
<section id="how-long-does-it-take-customers-to-return" class="level3">
<h3 class="anchored" data-anchor-id="how-long-does-it-take-customers-to-return">How long does it take customers to return?</h3>
<p>Among customers who made a qualifying second purchase, the median time between the first and second order was <strong>74.8 days</strong>. The mean was considerably higher at <strong>116.3 days</strong>, indicating <strong>a right-skewed distribution</strong>.</p>
<p>The shortest observed interval was approximately one day, while the longest was approximately 609 days.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-second-order-time" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-second-order-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="olist_analysis_files/figure-html/fig-second-order-time-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-second-order-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of the time between the first and second order.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The difference between the median and mean suggests that most returning customers purchase again relatively soon, while a smaller number return much later. The median of approximately 75 days therefore provides a more representative measure of typical repeat purchase timing than the mean.</p>
</section>
<section id="do-first-order-characteristics-differ-between-customer-groups" class="level3">
<h3 class="anchored" data-anchor-id="do-first-order-characteristics-differ-between-customer-groups">Do first-order characteristics differ between customer groups?</h3>
<p>The next step compares the first orders of customers who did and did not make a repeat purchase.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 13
  repeat_purchase customers median_order_value mean_order_value median_items
            &lt;dbl&gt;     &lt;int&gt;              &lt;dbl&gt;            &lt;dbl&gt;        &lt;dbl&gt;
1               0     94319               86.9             138.            1
2               1      2074               85.1             129.            1
# ℹ 8 more variables: mean_items &lt;dbl&gt;, median_freight &lt;dbl&gt;,
#   mean_freight &lt;dbl&gt;, median_delivery_days &lt;dbl&gt;, mean_delivery_days &lt;dbl&gt;,
#   median_review_score &lt;dbl&gt;, mean_review_score &lt;dbl&gt;,
#   late_delivery_rate &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The descriptive comparison shows relatively small differences in first-order value between the two groups. The median order value was approximately 86.9€ among customers without an observed repeat purchase and <strong>85.1€</strong> among repeat customers. Mean order value was also slightly lower among repeat customers (<strong>129€ compared with 138€</strong>).</p>
<p>A more noticeable difference was found in the number of items purchased. The mean number of items was 1.14 among customers without a repeat purchase and 1.21 among repeat customers.</p>
<p>This suggests that customers purchasing several items in their first order may be somewhat more likely to return, although the difference alone does not establish a causal relationship.</p>
</section>
<section id="does-the-first-product-category-matter" class="level3">
<h3 class="anchored" data-anchor-id="does-the-first-product-category-matter">Does the first product category matter?</h3>
<p>The first-order product category was also examined. To avoid unstable estimates based on very small customer groups, categories with fewer than 100 customers were excluded from the descriptive comparison.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-category-repeat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-category-repeat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="olist_analysis_files/figure-html/fig-category-repeat-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-category-repeat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Repeat purchase rate by first-order product category. Categories with fewer than 100 customers are excluded.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are clear differences in observed repeat purchase rates between product categories. Among categories with at least 100 customers, the highest observed rates included men’s fashion (4.67%), fashion underwear and beachwear (4.24%), beverages (3.96%), and fashion bags and accessories (3.61%).</p>
<p>However, the smallest categories also have relatively few repeat customers, so individual percentages should not be overinterpreted.</p>
<p>A Pearson chi-squared test with a simulated p-value was used because the category data contain many groups with relatively small counts.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with simulated p-value (based on 10000
    replicates)

data:  table(first_order_analysis$first_order_category, first_order_analysis$repeat_purchase)
X-squared = 158.86, df = NA, p-value = 2e-04</code></pre>
</div>
</div>
<p>The test produced <strong>a simulated p-value below 0.001</strong>, indicating that the distribution of repeat purchases differs across first-order categories. This provides evidence of an association between the category of the first purchase and subsequent repeat purchasing.</p>
<p>The result does not, however, mean that purchasing a particular category causes customers to return. Category differences may reflect other characteristics of the products or customers.</p>
</section>
<section id="can-repeat-purchases-be-predicted-from-the-first-order" class="level3">
<h3 class="anchored" data-anchor-id="can-repeat-purchases-be-predicted-from-the-first-order">Can repeat purchases be predicted from the first order?</h3>
<p>To examine whether repeat purchases can be predicted using information available from the first order, a logistic regression model was estimated.</p>
<p>The model included:</p>
<ul>
<li>first-order value</li>
<li>number of items</li>
<li>freight value</li>
<li>first-order product category</li>
</ul>
<p>The data were divided into training and test sets, with 80% of observations used for training and 20% for testing.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = repeat_purchase ~ order_value + number_of_items + 
    freight_value + first_order_category, family = binomial, 
    data = train_data)

Coefficients:
                                                                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                                                        -4.401e+00  7.141e-01  -6.163 7.15e-10 ***
order_value                                                        -5.705e-05  1.453e-04  -0.393    0.694    
number_of_items                                                     1.856e-01  3.989e-02   4.652 3.29e-06 ***
freight_value                                                      -2.242e-03  1.638e-03  -1.369    0.171    
first_order_categoryalimentos                                      -2.240e-01  8.726e-01  -0.257    0.797    
first_order_categoryalimentos_bebidas                              -1.880e-01  1.007e+00  -0.187    0.852    
first_order_categoryartes                                          -1.086e-01  1.007e+00  -0.108    0.914    
first_order_categoryartigos_de_natal                                1.083e+00  8.771e-01   1.234    0.217    
first_order_categoryaudio                                           5.949e-01  8.089e-01   0.735    0.462    
first_order_categoryautomotivo                                      2.913e-01  7.250e-01   0.402    0.688    
first_order_categorybebes                                           1.060e-01  7.327e-01   0.145    0.885    
first_order_categorybebidas                                         7.956e-01  8.101e-01   0.982    0.326    
first_order_categorybeleza_saude                                    3.030e-01  7.181e-01   0.422    0.673    
first_order_categorybrinquedos                                      1.772e-01  7.268e-01   0.244    0.807    
first_order_categorycama_mesa_banho                                 6.456e-01  7.165e-01   0.901    0.368    
first_order_categorycasa_conforto                                   6.275e-01  8.090e-01   0.776    0.438    
first_order_categorycasa_construcao                                 5.508e-01  7.885e-01   0.699    0.485    
first_order_categoryclimatizacao                                    4.534e-01  8.735e-01   0.519    0.604    
first_order_categoryconsoles_games                                  9.504e-02  7.655e-01   0.124    0.901    
first_order_categoryconstrucao_ferramentas_construcao              -1.715e-01  8.077e-01  -0.212    0.832    
first_order_categoryconstrucao_ferramentas_iluminacao              -2.656e-01  1.007e+00  -0.264    0.792    
first_order_categoryconstrucao_ferramentas_jardim                   8.958e-01  8.458e-01   1.059    0.290    
first_order_categoryconstrucao_ferramentas_seguranca               -5.718e-01  1.231e+00  -0.464    0.642    
first_order_categorycool_stuff                                      8.478e-02  7.292e-01   0.116    0.907    
first_order_categoryeletrodomesticos                                3.005e-01  7.810e-01   0.385    0.700    
first_order_categoryeletrodomesticos_2                             -8.814e-01  1.230e+00  -0.717    0.474    
first_order_categoryeletronicos                                     6.117e-02  7.365e-01   0.083    0.934    
first_order_categoryeletroportateis                                -1.241e-01  8.221e-01  -0.151    0.880    
first_order_categoryesporte_lazer                                   6.429e-01  7.173e-01   0.896    0.370    
first_order_categoryfashion_bolsas_e_acessorios                     9.830e-01  7.269e-01   1.352    0.176    
first_order_categoryfashion_calcados                                8.962e-01  8.251e-01   1.086    0.277    
first_order_categoryfashion_roupa_masculina                         1.417e+00  8.488e-01   1.670    0.095 .  
first_order_categoryfashion_underwear_e_moda_praia                  1.178e+00  8.777e-01   1.342    0.180    
first_order_categoryferramentas_jardim                              5.631e-01  7.231e-01   0.779    0.436    
first_order_categoryindustria_comercio_e_negocios                   1.788e-01  9.203e-01   0.194    0.846    
first_order_categoryinformatica_acessorios                          1.877e-01  7.206e-01   0.260    0.795    
first_order_categoryinstrumentos_musicais                           4.796e-02  8.075e-01   0.059    0.953    
first_order_categorylivros_interesse_geral                          4.589e-01  7.886e-01   0.582    0.561    
first_order_categorylivros_tecnicos                                -1.120e+00  1.230e+00  -0.910    0.363    
first_order_categorymalas_acessorios                                1.435e-01  7.656e-01   0.187    0.851    
first_order_categorymarket_place                                    3.200e-01  8.735e-01   0.366    0.714    
first_order_categorymoveis_cozinha_area_de_servico_jantar_e_jardim -2.334e-01  1.007e+00  -0.232    0.817    
first_order_categorymoveis_decoracao                                6.799e-01  7.181e-01   0.947    0.344    
first_order_categorymoveis_escritorio                               1.722e-01  7.567e-01   0.228    0.820    
first_order_categorymoveis_sala                                     1.111e+00  7.673e-01   1.448    0.148    
first_order_categoryother                                           4.023e-01  7.323e-01   0.549    0.583    
first_order_categorypapelaria                                       2.859e-01  7.336e-01   0.390    0.697    
first_order_categorypcs                                            -1.119e+01  1.225e+02  -0.091    0.927    
first_order_categoryperfumaria                                      5.226e-01  7.250e-01   0.721    0.471    
first_order_categorypet_shop                                        5.837e-01  7.342e-01   0.795    0.427    
first_order_categoryrelogios_presentes                              1.539e-01  7.225e-01   0.213    0.831    
first_order_categorysinalizacao_e_seguranca                         2.683e-01  1.009e+00   0.266    0.790    
first_order_categorytelefonia                                       3.590e-01  7.236e-01   0.496    0.620    
first_order_categorytelefonia_fixa                                  1.062e+00  8.100e-01   1.311    0.190    
first_order_categoryutilidades_domesticas                           3.660e-01  7.206e-01   0.508    0.612    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 15674  on 76545  degrees of freedom
Residual deviance: 15530  on 76491  degrees of freedom
AIC: 15640

Number of Fisher Scoring iterations: 14</code></pre>
</div>
</div>
<p>The number of items in the first order was the clearest continuous predictor in the model. Its coefficient was positive and <strong>statistically significant (p &lt; 0.001)</strong>. This indicates that customers who purchased more items in their first order tended to have higher odds of making a repeat purchase.</p>
<p>Order value and freight value were not statistically significant predictors in the model.</p>
<p>Although the category-level coefficients varied, most individual category effects were not statistically significant. This is consistent with the large number of categories and relatively small number of repeat purchases.</p>
</section>
<section id="how-well-can-repeat-purchases-be-predicted" class="level3">
<h3 class="anchored" data-anchor-id="how-well-can-repeat-purchases-be-predicted">How well can repeat purchases be predicted?</h3>
<p>The model was evaluated using the test data and the area under the ROC curve (AUC).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.5458</code></pre>
</div>
</div>
<p>The resulting AUC was <strong>0.546</strong>.</p>
<p>An AUC of 0.5 corresponds to random classification. Therefore, the model’s performance is only slightly better than random prediction.</p>
<p>This is an important finding. Although some variables are statistically associated with repeat purchasing, the available first-order information does not provide strong enough predictive power to reliably identify which individual customers will return.</p>
</section>
<section id="findings" class="level3">
<h3 class="anchored" data-anchor-id="findings">Findings</h3>
<p>Overall, the analysis produces four main findings.</p>
<ol type="1">
<li><p><strong>Repeat purchasing is relatively uncommon.</strong> Only approximately 2.2% of unique customers made an observed second purchase at least one day after their first order.</p></li>
<li><p><strong>Returning customers typically return after several weeks.</strong> The median time to a second order was approximately 75 days, although some customers returned substantially later.</p></li>
<li><p><strong>Product category is associated with repeat purchasing.</strong> The chi-squared test indicates statistically significant differences in repeat purchasing across first-order categories. However, small category sizes mean that individual category percentages should be interpreted cautiously.</p></li>
<li><p><strong>Predicting individual repeat purchases is difficult.</strong> The number of items in the first order was positively associated with repeat purchasing, but the logistic regression model achieved an AUC of only 0.546 on unseen data. This suggests that the variables available from the first purchase are not sufficient for accurate individual-level prediction.</p></li>
</ol>
<p>Taken together, the results suggest that customer retention is a potential business opportunity, but the available transaction-level variables do not provide a strong basis for predicting individual repeat customers. The next analysis can therefore focus on understanding <strong>customer value and which customer segments represent the greatest retention opportunity</strong>.</p>
</section>
</section>
<section id="research-question-2-customer-value" class="level2">
<h2 class="anchored" data-anchor-id="research-question-2-customer-value">Research Question 2: Customer Value</h2>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question</h3>
<p><strong>Which customers are most valuable, and can high-value customers be identified using information from their first purchase?</strong></p>
<p>The previous analysis focused on whether a customer makes another purchase. However, repeat purchasing alone does not describe the economic value of a customer. A customer who makes several small purchases may generate less revenue than a customer who makes fewer but substantially larger purchases.</p>
<p>Therefore, this part of the analysis focuses on customer value. Customers are classified as high-value customers if their total spending is in the top 10% of the customer distribution. The analysis then examines how customer value is distributed and whether high-value customers can be identified using information available from their first purchase.</p>
</section>
<section id="customer-value" class="level3">
<h3 class="anchored" data-anchor-id="customer-value">Customer Value</h3>
<p>Customer value is calculated by aggregating all orders belonging to the same <code>customer_unique_id</code>. For each customer, total spending, total freight costs, number of orders, number of items, and average order value are calculated.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  high_value_customer customers median_total_spend mean_total_spend median_number_of_orders mean_number_of_orders
  &lt;lgl&gt;                   &lt;int&gt;              &lt;dbl&gt;            &lt;dbl&gt;                   &lt;dbl&gt;                 &lt;dbl&gt;
1 FALSE                   86753                 79             92.3                       1                  1.03
2 TRUE                     9640                420            586.                        1                  1.12</code></pre>
</div>
</div>
<p>The results show a clear difference between high-value and other customers. The median total spending among high-value customers is <strong>420€</strong>, compared with <strong>78.90€</strong> among other customers. High-value customers also place slightly more orders on average.</p>
</section>
<section id="revenue-concentration" class="level3">
<h3 class="anchored" data-anchor-id="revenue-concentration">Revenue Concentration</h3>
<p>High-value customers represent only <strong>10% of the customer base</strong>, but they account for <strong>41.4% of total customer spending</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  high_value_customers total_customers high_value_share high_value_revenue_share
                 &lt;int&gt;           &lt;int&gt;            &lt;dbl&gt;                    &lt;dbl&gt;
1                 9640           96393             10.0                     41.4</code></pre>
</div>
</div>
<p>This indicates that customer value is highly concentrated. A relatively small proportion of customers generates a disproportionately large share of total revenue.</p>
</section>
<section id="distribution-of-customer-spending" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-customer-spending">Distribution of Customer Spending</h3>
<p>The distribution of total customer spending is strongly right-skewed. Most customers spend relatively small amounts, while a small number of customers have substantially higher total spending.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="olist_analysis_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of total customer spending. The x-axis is limited to the 99th percentile for visual clarity.</figcaption>
</figure>
</div>
</div>
</div>
<p>The high concentration of spending supports the use of a high-value customer segment rather than relying only on average customer spending.</p>
</section>
<section id="high-value-customers-by-first-order-category" class="level3">
<h3 class="anchored" data-anchor-id="high-value-customers-by-first-order-category">High-Value Customers by First-Order Category</h3>
<p>The first-order category is also compared across high-value and other customers.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 5
   first_order_category                           customers high_value_customers high_value_rate median_total_spend
   &lt;chr&gt;                                              &lt;int&gt;                &lt;int&gt;           &lt;dbl&gt;              &lt;dbl&gt;
 1 pcs                                                  176                  175            99.4             1200  
 2 agro_industria_e_comercio                            178                   93            52.2              391. 
 3 eletrodomesticos_2                                   225                  104            46.2              230. 
 4 instrumentos_musicais                                612                  184            30.1              127. 
 5 construcao_ferramentas_seguranca                     158                   46            29.1              140. 
 6 eletroportateis                                      616                  179            29.1              109  
 7 moveis_cozinha_area_de_servico_jantar_e_jardim       238                   54            22.7              130. 
 8 climatizacao                                         242                   54            22.3              139  
 9 construcao_ferramentas_construcao                    720                  143            19.9              100.0
10 moveis_escritorio                                   1239                  233            18.8              170. 
11 casa_construcao                                      463                   83            17.9              120. 
12 relogios_presentes                                  5431                  972            17.9              144  
13 consoles_games                                      1041                  180            17.3               69.9
14 moveis_sala                                          391                   64            16.4              115. 
15 construcao_ferramentas_iluminacao                    229                   36            15.7              169  </code></pre>
</div>
</div>
<p>The high-value rate varies substantially across first-order product categories. Among categories with at least 100 customers, <strong>pcs</strong> has by far the highest high-value rate at <strong>99.4%</strong>, although this category contains only 176 customers. The next highest rates are observed for <strong>agro_industria_e_comercio (52.2%)</strong> and <strong>eletrodomesticos_2 (46.2%)</strong>.</p>
<p>Other categories with relatively high high-value rates include <strong>instrumentos_musicais (30.1%)</strong>, <strong>construcao_ferramentas_seguranca (29.1%)</strong>, and <strong>eletroportateis (29.1%)</strong>. In contrast, larger categories such as <strong>relogios_presentes</strong>, with 5,431 customers, have a more moderate high-value rate of <strong>17.9%</strong>.</p>
<p>The results suggest that the product category of the first purchase may be associated with subsequent customer value. However, the highest rates in some categories are based on relatively small customer groups, so these results should be interpreted with caution.</p>
</section>
<section id="predicting-high-value-customers" class="level3">
<h3 class="anchored" data-anchor-id="predicting-high-value-customers">Predicting High-Value Customers</h3>
<p>The next step is to test whether high-value customers can be identified using information available from their first purchase.</p>
<p>A logistic regression model is used with high-value customer status as the outcome. The predictors describe the first purchase:</p>
<ul>
<li><p>order value</p></li>
<li><p>number of items</p></li>
<li><p>freight value</p></li>
<li><p>delivery time</p></li>
<li><p>review score</p></li>
<li><p>first-order product category</p></li>
</ul>
<p>The model is evaluated on a separate test set using ROC-AUC.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = high_value_customer ~ order_value + number_of_items + 
    freight_value + delivery_days + review_score + first_order_category, 
    family = binomial, data = train_data_value)

Coefficients:
                                                                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                                                        -1.084e+01  6.681e-01 -16.229   &lt;2e-16 ***
order_value                                                         3.614e-02  4.901e-04  73.742   &lt;2e-16 ***
number_of_items                                                     2.468e-02  4.393e-02   0.562   0.5743    
freight_value                                                      -2.978e-03  1.309e-03  -2.276   0.0229 *  
delivery_days                                                      -2.143e-03  3.053e-03  -0.702   0.4827    
review_score                                                       -2.425e-03  2.198e-02  -0.110   0.9121    
first_order_categoryalimentos                                       1.003e+00  9.949e-01   1.008   0.3133    
first_order_categoryalimentos_bebidas                               9.754e-01  1.221e+00   0.799   0.4245    
first_order_categoryartes                                           1.216e-01  1.366e+00   0.089   0.9291    
first_order_categoryartigos_de_natal                                4.328e-01  1.407e+00   0.308   0.7583    
first_order_categoryaudio                                          -9.681e-01  1.104e+00  -0.877   0.3805    
first_order_categoryautomotivo                                      7.296e-01  6.539e-01   1.116   0.2645    
first_order_categorybebes                                           4.172e-01  6.653e-01   0.627   0.5307    
first_order_categorybebidas                                        -1.813e+00  2.655e+00  -0.683   0.4948    
first_order_categorybeleza_saude                                    1.157e+00  6.458e-01   1.792   0.0731 .  
first_order_categorybrinquedos                                      6.957e-01  6.529e-01   1.066   0.2866    
first_order_categorycama_mesa_banho                                 1.172e+00  6.458e-01   1.815   0.0695 .  
first_order_categorycasa_conforto                                   3.836e-01  7.202e-01   0.533   0.5943    
first_order_categorycasa_construcao                                 1.298e+00  7.231e-01   1.795   0.0727 .  
first_order_categoryclimatizacao                                    1.422e+00  7.522e-01   1.890   0.0588 .  
first_order_categoryconsoles_games                                  1.218e+00  6.992e-01   1.742   0.0815 .  
first_order_categoryconstrucao_ferramentas_construcao               1.138e+00  6.984e-01   1.630   0.1032    
first_order_categoryconstrucao_ferramentas_iluminacao               4.737e-01  7.274e-01   0.651   0.5149    
first_order_categoryconstrucao_ferramentas_jardim                  -5.433e-01  1.363e+00  -0.398   0.6903    
first_order_categoryconstrucao_ferramentas_seguranca                1.422e+00  8.258e-01   1.722   0.0851 .  
first_order_categorycool_stuff                                      1.064e-01  6.537e-01   0.163   0.8707    
first_order_categoryeletrodomesticos                                1.297e+00  7.949e-01   1.632   0.1028    
first_order_categoryeletrodomesticos_2                             -4.797e-01  9.305e-01  -0.516   0.6062    
first_order_categoryeletronicos                                     6.460e-01  7.121e-01   0.907   0.3643    
first_order_categoryeletroportateis                                 1.474e+00  7.157e-01   2.059   0.0395 *  
first_order_categoryesporte_lazer                                   8.623e-01  6.463e-01   1.334   0.1821    
first_order_categoryfashion_bolsas_e_acessorios                     7.773e-01  6.990e-01   1.112   0.2661    
first_order_categoryfashion_calcados                                2.051e+00  7.980e-01   2.570   0.0102 *  
first_order_categoryfashion_roupa_masculina                         1.037e+00  1.080e+00   0.960   0.3372    
first_order_categoryfashion_underwear_e_moda_praia                  1.948e+00  1.205e+00   1.616   0.1061    
first_order_categoryferramentas_jardim                              9.971e-01  6.601e-01   1.511   0.1309    
first_order_categoryindustria_comercio_e_negocios                   5.248e-01  9.974e-01   0.526   0.5988    
first_order_categoryinformatica_acessorios                          8.835e-01  6.479e-01   1.364   0.1726    
first_order_categoryinstrumentos_musicais                           5.745e-01  6.991e-01   0.822   0.4112    
first_order_categorylivros_interesse_geral                          9.702e-01  1.016e+00   0.955   0.3395    
first_order_categorylivros_tecnicos                                -1.232e+00  1.180e+00  -1.044   0.2963    
first_order_categorymalas_acessorios                                6.407e-01  6.699e-01   0.956   0.3389    
first_order_categorymarket_place                                    7.752e-01  8.171e-01   0.949   0.3427    
first_order_categorymoveis_cozinha_area_de_servico_jantar_e_jardim  1.081e+00  7.953e-01   1.359   0.1741    
first_order_categorymoveis_decoracao                                1.170e+00  6.465e-01   1.809   0.0704 .  
first_order_categorymoveis_escritorio                               6.568e-01  6.611e-01   0.994   0.3205    
first_order_categorymoveis_sala                                     1.488e+00  7.483e-01   1.989   0.0467 *  
first_order_categoryother                                           8.423e-01  7.116e-01   1.184   0.2366    
first_order_categorypapelaria                                       8.434e-01  6.824e-01   1.236   0.2165    
first_order_categorypcs                                             1.343e+00  4.436e+01   0.030   0.9759    
first_order_categoryperfumaria                                      8.135e-01  6.509e-01   1.250   0.2113    
first_order_categorypet_shop                                        9.856e-01  6.760e-01   1.458   0.1449    
first_order_categoryrelogios_presentes                              3.052e-01  6.466e-01   0.472   0.6369    
first_order_categorysinalizacao_e_seguranca                         1.050e+00  9.826e-01   1.069   0.2851    
first_order_categorytelefonia                                       8.493e-01  6.580e-01   1.291   0.1968    
first_order_categorytelefonia_fixa                                  5.110e-01  8.943e-01   0.571   0.5677    
first_order_categoryutilidades_domesticas                           6.549e-01  6.523e-01   1.004   0.3154    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 48418.7  on 73751  degrees of freedom
Residual deviance:  9148.4  on 73695  degrees of freedom
AIC: 9262.4

Number of Fisher Scoring iterations: 14</code></pre>
</div>
</div>
<p>The strongest predictor is the value of the first order. The coefficient for order_value is positive and highly statistically significant, indicating that customers with larger first purchases are substantially more likely to belong to the high-value customer group.</p>
<p>Most individual product categories are not statistically significant after controlling for the other first-order characteristics.</p>
</section>
<section id="model-performance" class="level3">
<h3 class="anchored" data-anchor-id="model-performance">Model Performance</h3>
<p>The model achieves a ROC-AUC of <strong>0.98</strong> on the test data.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9780744</code></pre>
</div>
</div>
<p>An AUC of approximately 0.98 indicates excellent discrimination between high-value and other customers in the test data.</p>
<p>However, the very high AUC should be interpreted with care. High-value status is defined using customers’ total spending, while first-order value is included as a predictor. Therefore, a large first purchase naturally provides strong information about whether the customer’s eventual total spending will be high.</p>
<p>The result should therefore not be interpreted as evidence that high-value customers can be identified perfectly from general behavioral characteristics. Instead, it shows that <strong>initial purchase value is a very strong indicator of eventual customer value in this dataset</strong>.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The analysis shows a strong concentration of customer value in the Olist data. The top 10% of customers account for <strong>41.4% of total spending</strong>, while their median spending is substantially higher than that of other customers.</p>
<p>The predictive analysis also shows that high-value customers can be distinguished very accurately using first-order information, with a test-set ROC-AUC of <strong>0.98</strong>.. The dominant predictor is the value of the first purchase.</p>
<p>This provides a different perspective from the first research question. While repeat purchasing was relatively difficult to predict from first-order characteristics, customer value was much more strongly associated with the initial order value.</p>
</section>
</section>
<section id="research-question-3-delivery-experience-and-customer-satisfaction" class="level2">
<h2 class="anchored" data-anchor-id="research-question-3-delivery-experience-and-customer-satisfaction">Research Question 3: Delivery Experience and Customer Satisfaction</h2>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question</h3>
<p><strong>How is delivery performance associated with customer satisfaction and repeat purchasing?</strong></p>
<p>The previous analyses focused on customer retention and customer value. This part of the analysis examines whether the delivery experience is associated with customer satisfaction and customers’ likelihood of making another purchase.</p>
<p>The analysis compares on-time and late deliveries using review scores and repeat-purchase rates. Statistical tests are also used to evaluate whether the observed differences are unlikely to be due to random variation.</p>
</section>
<section id="delivery-performance-and-repeat-purchasing" class="level3">
<h3 class="anchored" data-anchor-id="delivery-performance-and-repeat-purchasing">Delivery Performance and Repeat Purchasing</h3>
<p>The delivery experience differs somewhat between customers who do and do not make another purchase.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  repeat_purchase customers median_delivery_days mean_delivery_days late_delivery_rate median_review_score mean_review_score
            &lt;dbl&gt;     &lt;int&gt;                &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;               &lt;dbl&gt;             &lt;dbl&gt;
1               0     94319                 10.2               12.6               8.19                   5              4.08
2               1      2074                 10.0               11.9               5.90                   5              4.19</code></pre>
</div>
</div>
<p>Repeat customers experienced slightly fewer late deliveries than non-repeat customers. The late-delivery rate was <strong>5.91%</strong> among repeat customers compared with <strong>8.19%</strong> among customers who did not make another observed repeat purchase.</p>
<p>The average delivery time was also slightly shorter among repeat customers, at <strong>11.9 days</strong> compared with <strong>12.6 days</strong> among non-repeat customers. However, the difference in delivery time itself is relatively small.</p>
</section>
<section id="delivery-performance-and-review-scores" class="level3">
<h3 class="anchored" data-anchor-id="delivery-performance-and-review-scores">Delivery Performance and Review Scores</h3>
<p>A much stronger difference can be observed in customer review scores.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  delivered_late customers median_review_score mean_review_score
           &lt;dbl&gt;     &lt;int&gt;               &lt;dbl&gt;             &lt;dbl&gt;
1              0     85463                   5              4.29
2              1      7458                   2              2.56</code></pre>
</div>
</div>
<p>Customers whose orders were delivered on time gave an average review score of <strong>4.29</strong>, while customers whose orders were delivered late gave an average score of only <strong>2.56</strong>.</p>
<p>The median review score was <strong>5</strong> for on-time deliveries and <strong>2</strong> for late deliveries. This indicates a substantial relationship between delivery performance and customer satisfaction.</p>
<p>The difference in review scores was tested using a Wilcoxon rank-sum test.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  review_score by delivered_late
W = 495413418, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>The test produced a <strong>p-value below 2.2 × 10⁻¹⁶</strong>, providing very strong statistical evidence that review-score distributions differ between on-time and late deliveries.</p>
</section>
<section id="review-scores-by-delivery-status" class="level3">
<h3 class="anchored" data-anchor-id="review-scores-by-delivery-status">Review Scores by Delivery Status</h3>
<p>The difference can also be seen visually in the distribution of review scores.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="olist_analysis_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Review scores for on-time and late deliveries.</figcaption>
</figure>
</div>
</div>
</div>
<p>The distribution shows that late deliveries are associated with substantially lower review scores.</p>
</section>
<section id="delivery-performance-and-repeat-purchases" class="level3">
<h3 class="anchored" data-anchor-id="delivery-performance-and-repeat-purchases">Delivery Performance and Repeat Purchases</h3>
<p>The repeat-purchase rate was also compared between on-time and late deliveries.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  delivered_late customers repeat_customers repeat_rate
           &lt;dbl&gt;     &lt;int&gt;            &lt;dbl&gt;       &lt;dbl&gt;
1              0     85922             1883        2.19
2              1      7614              118        1.55</code></pre>
</div>
</div>
<p>The repeat-purchase rate was <strong>2.19%</strong> for customers whose first order was delivered on time, compared with <strong>1.55%</strong> for customers whose first order was delivered late.</p>
<p>A chi-squared test was used to evaluate the association between delivery status and repeat purchasing.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with simulated p-value (based on 10000 replicates)

data:  table(first_order_analysis$delivered_late, first_order_analysis$repeat_purchase)
X-squared = 13.759, df = NA, p-value = 5e-04</code></pre>
</div>
</div>
<p>The test produced a <strong>p-value of 0.0006</strong>, indicating a statistically significant association between delivery status and repeat purchasing.</p>
<p>The difference is relatively small in absolute terms, however. Therefore, delivery performance appears to have a much stronger relationship with customer satisfaction than with repeat purchasing in this dataset.</p>
</section>
<section id="repeat-purchase-rate-by-delivery-status" class="level3">
<h3 class="anchored" data-anchor-id="repeat-purchase-rate-by-delivery-status">Repeat Purchase Rate by Delivery Status</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="olist_analysis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Repeat-purchase rate for customers with on-time and late first deliveries.</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure shows the lower repeat-purchase rate among customers whose first order was delivered late. Although the difference is statistically significant, the effect is considerably smaller than the difference observed in review scores.</p>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>The analysis shows a strong association between delivery performance and customer satisfaction. Late deliveries are associated with substantially lower review scores, with the average score falling from <strong>4.29</strong> for on-time deliveries to <strong>2.56</strong> for late deliveries.</p>
<p>Delivery performance is also statistically associated with repeat purchasing. Customers with on-time first deliveries had a repeat-purchase rate of <strong>2.19%</strong>, compared with <strong>1.55%</strong> among customers whose first delivery was late.</p>
<p>However, the results should be interpreted as <strong>associations rather than causal effects</strong>. Other factors may influence both delivery performance and customer behavior. Nevertheless, the results suggest that reliable delivery is strongly related to customer satisfaction and may also be relevant for customer retention.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>